# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2467d65d722402a84ed34b566e7d70ad8ad01af854b4a794db5cc26f0a76b2e3a3de6397dcc33f990b6ff745b357500ae6d2f88c77af51c8352f7a1a3efb748

test:
  secret_key_base: 157f2c4d983300a7a1bc274551a8c092e21507ae8240764b2306b548ff0366d03bbefacbcb6edf174534d7fcb1eb238875730961b39a7f14a975e75cb545b579

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
